### ISSUE TITLE
Captcha overuse

### ISSUE THREAD

**Issue by Petterholm** [ShuffleDATMT/PTC-Creator#13] opened 2018-03-23 16:39 UTC
![capture2](https://user-images.githubusercontent.com/16854912/37841940-2cf2615a-2ec1-11e8-947f-ff9c7fa2b9dd.PNG)
![capture](https://user-images.githubusercontent.com/16854912/37841941-2d0c9dae-2ec1-11e8-867f-476b27fb1686.PNG)

**Comment by Petterholm** [comment] 2018-03-23 16:40
Slightly over usage? Only been using anti for this creator...

**Comment by ShuffleDATMT** [comment] 2018-03-23 16:40
You sold 20k accounts in the past 24 hours?

**Comment by ShuffleDATMT** [comment] 2018-03-23 16:44
Well. This never happen to me

**Comment by ShuffleDATMT** [comment] 2018-03-23 16:45
And I told you it matched up perfectly in the issue when I ran a test
https://github.com/ShuffleDATMT/PTC-Creator/issues/10

**Comment by Petterholm** [comment] 2018-03-23 16:45
Yes i know, but this is very weird. What do u suggest? re-install?

**Comment by ShuffleDATMT** [comment] 2018-03-23 16:46
From ADS database, you took 3k and sold 5k. So it should be around 12k difference. I will take a close look

**Comment by Petterholm** [comment] 2018-03-23 16:47
Ah yeah forgot about the 3k, okay sure. I will stop the bot while im waiting for an fix

**Comment by Petterholm** [comment] 2018-03-23 16:47
First thing i thought was because of fails but i have about 91% rate so that shouldnt be it

**Comment by ShuffleDATMT** [comment] 2018-03-23 17:01
I am running another test. Let's see how it goes in 1 hour

**Comment by Petterholm** [comment] 2018-03-23 17:01
Okay

**Comment by ShuffleDATMT** [comment] 2018-03-23 17:49
I will add a new form to show logs including captcha logs. And I will push the version up in few hours. If you identify any of the account submitting more then one captchas, let me know. Results works fine for me

**Comment by Petterholm** [comment] 2018-03-23 17:49
Okay

**Comment by ShuffleDATMT** [comment] 2018-03-23 18:09
@Petterholm @Benney29 Can you download the new version and test it?

**Comment by Petterholm** [comment] 2018-03-23 19:10
Downloaded, where can i locate this log?

**Comment by ShuffleDATMT** [comment] 2018-03-23 19:32
Right click on account show log

**Comment by Petterholm** [comment] 2018-03-23 19:35
Am i supposed to check every single acc? or is it another way

**Comment by Benney29** [comment] 2018-03-23 19:40
I did run the 1.0.8.0 version now for an hour, and it seems the Captcha overuse is solved in this version.
Only the hourly crash is still there. The account creator crashes every hour.

**Comment by ShuffleDATMT** [comment] 2018-03-23 19:42
1. I didn't solve anything about Captcha... I just add some logs to indicate there is no over usage of Captcha.
2. Once you encountered a crash, please check whether you have a message shows `JIT Debugger`. If yes, please post your log inside the git repo. I will use that log to fix. Or if you can locate the "log.txt" inside the PTC-Creator folder, that would also work

**Comment by Petterholm** [comment] 2018-03-23 19:43
crashed alot for me also earlier today, it just says PTC Creator crashed (something like that) and no log or any more info...

**Comment by ShuffleDATMT** [comment] 2018-03-23 19:45
I've updated the config file in 1.0.8 version I believe, if the issue is solved. Please close this issue and open another issue once you encounter another problem.

**Comment by Petterholm** [comment] 2018-03-23 22:49
![capture3](https://user-images.githubusercontent.com/16854912/37856436-c46ce95a-2ef4-11e8-9cea-f83ea0fc04f2.PNG)
![capture2](https://user-images.githubusercontent.com/16854912/37856437-c4868a4a-2ef4-11e8-8cd9-549caa49fb92.PNG)

**Comment by Petterholm** [comment] 2018-03-23 22:49
Guess i broke the system

**Comment by ShuffleDATMT** [comment] 2018-03-24 00:28
Image invalid. I don't know what exactly you did can you tell me more about it?

**Comment by ShuffleDATMT** [comment] 2018-03-24 00:29
You need to figure out how Anti-Captcha count captchas first

**Closed** 2018-03-24 08:03 UTC
Labels: invalid
